version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/hackathon/front
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 300
      runas: ec2-user
